[start]
name = "Start"
pushable = false
dragable = false
rotatable = false
max_activations = 1
prize = 1
cost = 0
sprite_name = "start.png"
program = [{ type = "Hit", arg = [[1, 0]] }]
description = "The alpha, the omega"

[hammer_time]
name = "Hammer time"
max_activations = 3
prize = 1
cost = 1
sprite_name = "hammer_time.png"
program = [{ type = "Hit", arg = [[1, 0]] }]
description = "Pokes toward its front."

[pusher]
name = "Andrew Pusher"
max_activations = 3
prize = 1
cost = 1
sprite_name = "pusher.png"
program = [{ type = "Push", arg = "Front" }]
description = "For anything pushing, there's the man.\n\nPushes once to the front."

[bowling_ball]
name = "Bowling ball"
max_activations = 3
prize = 1
cost = 2
sprite_name = "bowling_ball.png"
program = [
    { type = "Forward" },
    { type = "Forward" },
    { type = "Forward" },
    { type = "Hit", arg = [
        [
            1,
            0,
        ],
    ] },
]
description = "Rolls, rolls, rolls, then pokes toward the front."

[ballerina]
name = "Ballerina"
max_activations = 3
prize = 2
cost = 3
sprite_name = "ballerina.png"
program = [{ type = "Push", arg = "Right" }, { type = "Turn", arg = "Right" }]
description = "Dances to the front, pushing to the right; then faces her partner."

[good_boy]
name = "Good boy"
max_activations = 3
prize = 3
cost = 4
sprite_name = "good_boy.png"
program = [{ type = "Hit", arg = [[0, 1], [0, -1]] }, { type = "Forward" }]
description = "Waggles his tail left and right, poking around; then runs forward.\n\nCome here my boy !"


[desperado]
name = "Desperado"
max_activations = 3
prize = 3
cost = 6
sprite_name = "desperado.png"
program = [{ type = "Hit", arg = [[1, 0], [-1, 0], [2, 0], [-2, 0]] }]
description = "Keeps an eye on the front and on the back. Fires twice on both those sides."

[tombstone]
name = "Tombstone"
max_activations = 3
prize = 0
cost = 10
sprite_name = "tombstone.png"
program = [
    { type = "Hit", arg = [
        [
            1,
            0,
        ],
        [
            1,
            1,
        ],
        [
            0,
            1,
        ],
        [
            -1,
            1,
        ],
        [
            -1,
            0,
        ],
        [
            -1,
            -1,
        ],
        [
            0,
            -1,
        ],
        [
            1,
            -1,
        ],
    ] },
]
description = "There is no reward for poking the dead. Pokes every adjacent location with terror.\n\nCannot be pushed."
rotatable = false
pushable = false

[broom]
name = "Broom"
max_activations = 3
prize = 3
cost = 20
sprite_name = "broom.png"
program = [
    { type = "Turn", arg = "Left" },
    { type = "Push", arg = "Right" },
    { type = "Turn", arg = "Back" },
    { type = "Forward" },
    { type = "Push", arg = "Left" },
    { type = "Turn", arg = "Back" },
    { type = "Forward" },
    { type = "Turn", arg = "Right" },
    { type = "Push", arg = "Front" },
]
description = "Pushes three columns toward its front.\n\nThat's some heavy duty cleaning !"
