[start]
name = "Start"
pushable = false
dragable = false
rotatable = false
max_activations = 1
prize = 1
cost = 0
sprite_name = "start.png"
program = [{ type = "Hit", arg = [[1, 0]] }]
description = "The alpha, the omega"

[hammer_time]
name = "Hammer time"
max_activations = 3
prize = 1
cost = 1
sprite_name = "hammer_time.png"
program = [{ type = "Hit", arg = [[1, 0]] }]
description = "Pokes toward its front."

[pusher]
name = "Andrew Pusher"
max_activations = 3
prize = 1
cost = 1
sprite_name = "pusher.png"
program = [{ type = "Push", arg = "Front" }]
description = "For anything pushing, there's the man.\n\nPushes once to the front."

[bowling_ball]
name = "Bowling ball"
max_activations = 3
prize = 1
cost = 2
sprite_name = "bowling_ball.png"
program = [
    { type = "Forward" },
    { type = "Forward" },
    { type = "Forward" },
    { type = "Hit", arg = [
        [
            1,
            0,
        ],
    ] },
]
description = "Rolls, rolls, rolls, then pokes toward the front."

# [ballerina]
# name = "Ballerina"
# max_activations = 3
# prize = 2
# cost = 3
# sprite_name = "ballerina.png"
# program = [{ type = "Push", arg = "Right" }, { type = "Turn", arg = "Right" }]
# description = "Dances to the front, pushing to the right, then faces her partner."
