[start]
name = "Start"
pushable = false
dragable = false
rotatable = false
max_activations = 1
prize = 1
cost = 0
sprite_name = "start.png"
program = [{ type = "Hit", arg = [[0, 1]] }]

[hammer_time]
name = "Hammer time"
max_activations = 3
prize = 1
cost = 1
sprite_name = "hammer_time.png"
program = [{ type = "Hit", arg = [[0, 1]] }]

[pusher]
name = "Pusher"
max_activations = 3
prize = 1
cost = 1
sprite_name = "pusher.png"
program = [{ type = "Push", arg = "Front" }]

[bowling_ball]
name = "Bowling ball"
max_activations = 3
prize = 1
cost = 2
sprite_name = "bowling_ball.png"
program = [{ type = "Forward" }, { type = "Hit", arg = [[0, 1]] }]
