[camera]
follow_decay = 500
zoom_min_tiles = 6
zoom_max_tiles = 48

[checker]
tile_size = 40

[game]
start_gold = 3
restock_multiplier = 1.5

[drag]
scale = 1.2
alpha = 0.4

[ui]
turn_startup_duration = 1.0
turn_startup_shake = 2.0
