[camera]
follow_decay = 500
turn_decay = 3.0
zoom_min_tiles = 6
zoom_max_tiles = 48

[checker]
tile_size = 40

[game]
start_gold = 20
restock_multiplier = 1.5

[drag]
scale = 1.2
alpha = 0.4

[ui]
turn_startup_duration = 1.0
turn_startup_shake = 2.0
activation_icon_size = 20.0
activation_icon_offset = 25.0

[particles]
drop_magnitude = 40
drop_count = 5
drop_duration = 0.7

[turn]
try_push_duration = 0.2
complete_push_duration = 0.1
cancel_push_duration = 0.1
activation_duration = 0.01
deactivation_duration = 0.01
hit_duration = 0.4
move_duration = 0.3
